package com.example.tourmanage.presenter.festival

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier

@Composable
fun TestScreen(modifier: Modifier) {
    Column(
        modifier = modifier.fillMaxSize()
//            .fillMaxSize().background(Color.Yellow), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.Center
    ) {
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")
        Text("This is Screen 1")

    }
}